version: '3.3'

services:
  db:
    image: mysql:8.0.22
    restart: always
    container_name: todoapp_db
    environment:
      MYSQL_ROOT_PASSWORD: "p@ssword"
      MYSQL_DATABASE: "together"
    ports:
      - "3306:3306"
